## The following requirements were added by pip freeze:
caniusepython3
coverage
descartes
distlib
Django
django-adaptors
django-extensions
django-pdb
django-shell-plus
Fiona
future
futures
geopandas
igraph
ipython
jupyter
jupyter-client
jupyter-console
jupyter-core
lxml
matplotlib
neo4django
neo4jrestclient
neomodel
networkx
notebook
numpy
pandas
pandas-datareader
psycopg2
py2neo
python-igraph
redis
scipy
Shapely
six
statsmodels
sympy
tensorflow
tensorflow-tensorboard
tornado
cartopy
